// This file was configured by VeriSolid found at https://github.com/VeriSolid/smart-contracts

// This file is automatically generated from the webgme-setup-tool.
'use strict'

const path = require('path')
const config = require('webgme/config/config.default')
const validateConfig = require('webgme/config/validator')

// Seed projects config
config.seedProjects.basePaths.push(path.join(__dirname, '/../src/seeds'))
config.seedProjects.defaultProject = 'Move-Smart-Contract'

// Visualization config
config.visualization.panelPaths.push(path.join(__dirname, '/../src/visualizers/panels'))
config.visualization.visualizerDescriptors.push(path.join(__dirname, '/../src/visualizers/Visualizers.json'))
config.visualization.decoratorPaths.push(path.join(__dirname, '/../src/decorators'))

// WebGME Client config
config.client.pageTitle = 'VeriMove'
config.client.faviconPath = '/extlib/favicon.ico'

// Add requirejs paths
config.requirejsPaths = {
  panels: './src/visualizers/panels',
  widgets: './src/visualizers/widgets',
  'move-smart-contracts': './src/common'
}

config.mongo.uri = 'mongodb://127.0.0.1:27017/move-smart-contracts'
validateConfig(config)
module.exports = config
